version: '3.1'

services:
  db:
    image: mysql
    container_name: shopkgp-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: god_speed
    networks:
      - shopkgp-net
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer
    container_name: shopkgp-adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - shopkgp-net

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: shopkgp-app
    restart: always
    environment:
      API_PORT: 3001
    depends_on:
      - db
    ports:
      - 3001:3001
    networks:
      - shopkgp-net
    volumes:
      - ./app:/home/app/*


networks:
  shopkgp-net: